name: fatprogs test CI

on:
  push:
    branches: [ "main", "next" ]
  pull_request:
    branches: [ "main", "next" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build fatprogs
      run: |
        make
        sudo make install
    - name: check fat test images
      run: |
        cd tests
        ./test_all_images.sh
